development:
  adapter: postgresql
  encoding: unicode
  database: api_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  database: api_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
